version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - cd day-14/simple-python-app
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "The Build is completed successfully."

artifacts:
  base-directory: day-14/simple-python-app
  files:
    - '**/*'
